### ISSUE TITLE
A better way to setup the config.js file

### ISSUE THREAD

**Issue by ryanseddon** [ryanseddon/bunyip#1]
Setting up the config.js file is silly it should be a command option to run you through the options perhaps? Can anyone suggest an approach or help?

**Comment by webxl** [comment]
I like having a config file, but it shouldn't be required to edit the one in the lib directory. Either or both of these would definitely help:

1) add a " -c path_to_config" option to bunyip.
2) add additional default locations for the config, like a dotfile (~/.bunyip) and ./config.js (working directory)

Perhaps you can use commander to walk through the options and generate ~/.bunyip

**Comment by ryanseddon** [comment]
Yeah that might be a good option. I'll want it to work on windows too so I'll investigate doing a commander walk through and the ability to specify your own default location for config.js.

**Comment by jayarjo** [comment]
I did add support for this on <a href="https://github.com/jayarjo/bunyip">my fork</a>, but then I went on with rewriting things here and there (couldn't resist to make it "more consistent"... ), so now I guess it can't be pulled in :|

**Comment by ryanseddon** [comment]
Perhaps you could create a branch and just do the config option changes in your fork? I'd happy to pull that in.

I'm liking some of the other stuff you've done too. The hub option is pretty much exactly as I have done it on my local copy and adds the feature I mention in issue #4.
