### ISSUE TITLE
Browserstack workers fail to connect to yeti

### ISSUE THREAD

**Issue by webxl** [ryanseddon/bunyip#2]
This happens with both the stock config.js file and a custom one. Here's what I'm trying to run:

```
$ bunyip -f test/jasmine.html -b "firefox:win/4.0,5.0,6.0|iPad:ios/3.2"  

BrowserStack iPad 3.2 worker launched: 208767
  BrowserStack firefox 4.0 worker launched: 208768
  BrowserStack firefox 6.0 worker launched: 208769
  BrowserStack firefox 5.0 worker launched: 208770
```

And nothing happens. It hangs until I kill it. The status command shows they're running, however:

```
$ bunyip -s
Running:
    iPad - 3.2 (208767) 
    firefox - 4.0 (208768) 
Queued:
    firefox - 6.0 (208769) 
    firefox - 5.0 (208770) 
```

It works fine from a local browser, or if I run `pagekite.py 9000 webxl.pagekite.me` before I run that command. I think node is failing to run pagekite. 

I'm on OS X 10.7, node v0.6.18

**Comment by ryanseddon** [comment]
Try just launching bunyip without any browserstack workers.

``` bash
bunyip -f test/jasmine.html
```

That still launches the tunnel. Open the browserstack web interface and load your tunnel link in a browser. If that works it usually means the API may be having some intermittent issues. cc: @ritesharora

**Comment by webxl** [comment]
OK. For some reason I had a bunch of pagekite processes running, perhaps because I didn't have the right settings, and that was causing issues. Killing them all solved my issue. I did notice problems with BrowserStack where one or more agents take forever to connect to the server:

```
$ bunyip -f test/jasmine.html -b ie:win/7.0,8.0
Creating a Hub at http://localhost:9000
Waiting for agents to connect at http://localhost:9000.
When ready, press Enter to begin testing.
  BrowserStack ie 8.0 worker launched: 226362
  BrowserStack ie 7.0 worker launched: 226363
  Agent connected: Internet Explorer (7.0) / Windows XP 64

```

It's probably because of high load, but if it keeps happening, I'll open another issue.
