### ISSUE TITLE
Cannot find cli.js

### ISSUE THREAD

**Issue by tinganho** [ryanseddon/bunyip#21]
I got this error when running bunyip config path/to/config.

```
Cannot find module '/Users/tinganho/code/bunyip/cli.js'
```

**Comment by ryanseddon** [comment]
Did you globally install it? If you can give me a little more context I can help you.

**Comment by tinganho** [comment]
Yes I installed it globally. Though I get a warning npm 

```
WARN engine bunyip@0.2.2: wanted: {"node":"~0.8.x"} (current: {"node":"v0.10.21","npm":"1.3.11"})
```

**Comment by ryanseddon** [comment]
I just tried with node v0.10.24 and didn't get that error.

Have you changed your global install location for npm? It could be that your directory isn't in your PATH?

**Comment by tinganho** [comment]
No I haven't changed the global install folder. It installs everything
in /usr/local/lib/node_modules. I can see that bunyip is there

On Mon, Dec 23, 2013 at 9:33 AM, Ryan Seddon notifications@github.comwrote:

> I just tried with node v0.10.24 and didn't get that error.
> 
> Have you changed your global install location for npm? It could be that
> your directory isn't in your PATH?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ryanseddon/bunyip/issues/21#issuecomment-31100951
> .

## 

Sincerely,

Tingan Ho
tingan@p1.cn

**Comment by tinganho** [comment]
Ok I found the problem. It turned out that it was some of my .dotfiles that was interfering with bunyip. Thanks for the help anyway. https://github.com/grayghostvisuals/dotfiles/blob/master/.aliases#L23

**Comment by ryanseddon** [comment]
Oh cool yeah the directory `/code` is what made me think you had some special npm setup.
